### ISSUE TITLE
Poster design

### ISSUE THREAD

**Issue by bsommerer** [kristinashevchenko/EveryoneArtist#38]

**Comment by kristinashevchenko** [comment]
starting page
![starting_page](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/0a1d0d82-890a-4869-a9d3-dd70d3d738a8)

1 set on conversation
conversation_without_image
![conversation_without_image](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/fd4dddc1-a398-4ce2-b00a-04093ab3324e)

conversation_with_image
![conversation_with_image](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/989542a3-7742-47e5-9be5-726741d58865)

conversation_with_image_edited_response
![conversation_with_image_edited_response](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/69ed4e54-f5db-49aa-9696-ff1c4a46042c)

conversation_with_image_new_chat_option
![conversation_with_image_new_chat_option](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/24b051e6-d020-4bb9-ae59-be1acb4a7319)

 lot_of_images
![lot_of_images](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/1eaa23fa-12e1-4eed-b74b-fa3d9f09a414)



2nd set of conversations (I like it more)
conversation_without_image
![conversation_without_image png_v2](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/9cfeb541-b6c0-4fb7-b83d-1e07465bef12)

conversation_with_image
![conversation_with_image_v2](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/de5186df-e951-4c5e-a5b9-9cacf04c025e)

conversation_with_image_edited_response
![conversation_with_image_edited_response_v2](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/77c9ec0c-1098-4883-a880-1a372ac61850)

conversation_without_image_new_chat_option
![conversation_without_image_new_chat_option_v2](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/c58fb65d-cab8-4b9d-8db6-4ebf475b07f9)

conversation_with_image_new_chat_option
![conversation_with_image_new_chat_option_v2](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/080b7db2-ed20-4c3e-bb01-1d4686356c8e)

conversation_with_several_images
![conversation_with_several_images](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/8e05afed-64ec-460b-adcc-6df44de10024)

more_images
![more_images_v2](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/efb2a4e8-f08e-4703-b314-aca8c33ff060)

**Comment by kristinashevchenko** [comment]
start page without cursor
![start](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/cb311286-0734-4c37-8972-77d65691abea)

**Comment by kristinashevchenko** [comment]
![nikon_screen](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/99f5dae3-6bfa-4441-bd25-d9775515f99d)
![canon_screen](https://github.com/kristinashevchenko/EveryoneArtist/assets/36192930/e92c5b51-db59-4447-a853-5a6c71729d0a)
